name: Web Check

permissions:
  contents: read

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [24.19]
        experimental: [false]
    name: 👷 CI @qwik.dev/astro Node-${{ matrix.node }} under ${{ matrix.os }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7

      - name: 🎉 Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml

      - name: ✨ Install dependencies
        run: |
          cd web
          corepack enable
          pnpm install

      - name: ✅ Check code style
        working-directory: web
        run: pnpm check

      - name: ✅ Build static site
        
        run: pnpm build
